
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NUMBER SYMBOLsplist : splist spsplist : spsp : SYMBOLsp : SYMBOL NUMBER'
    
_lr_action_items = {'SYMBOL':([0,1,2,3,4,5,],[3,3,-2,-3,-1,-4,]),'$end':([1,2,3,4,5,],[0,-2,-3,-1,-4,]),'NUMBER':([3,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'splist':([0,],[1,]),'sp':([0,1,],[2,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> splist","S'",1,None,None,None),
  ('splist -> splist sp','splist',2,'p_splist_sp','chemistry_caculate.py',15),
  ('splist -> sp','splist',1,'p_splist_to_sp','chemistry_caculate.py',19),
  ('sp -> SYMBOL','sp',1,'p_sp_symbol','chemistry_caculate.py',23),
  ('sp -> SYMBOL NUMBER','sp',2,'p_sp_symbol_count','chemistry_caculate.py',27),
]
